import { notFound } from 'next/navigation';
import Link from 'next/link';
import PageShell from '@/components/PageShell';
import { projects } from '@/data/projects';
import { ArrowLeft, ArrowUpRight } from 'lucide-react';

export function generateStaticParams(){ return projects.map(project => ({ slug: project.slug })); }
export async function generateMetadata({params}:{params:{slug:string}}){ const p=projects.find(x=>x.slug===params.slug); return p ? { title:`${p.title} — Aditya Kumar`, description:p.shortDescription } : {}; }
export default function ProjectDetail({params}:{params:{slug:string}}){ const p=projects.find(x=>x.slug===params.slug); if(!p) notFound(); return <PageShell><main className="section-pad"><div className="container-main max-w-6xl"><Link href="/portfolio" className="inline-flex items-center gap-2 text-xs text-[#65737a] hover:text-white"><ArrowLeft size={14}/> Back to portfolio</Link><div className="mt-10 flex flex-wrap items-center gap-4"><span className="project-index">{p.number}</span><span className="mono text-[10px] uppercase tracking-[.13em] text-[#65737a]">{p.category}</span><span className="status">{p.status}</span></div><h1 className="section-title mt-6 max-w-4xl">{p.title}</h1><p className="body-copy mt-6 max-w-3xl text-base">{p.shortDescription}</p><div className="mt-10 flex flex-wrap gap-2">{p.technologies.map(t=><span className="tag" key={t}>{t}</span>)}</div><div className="mt-16 grid gap-4 lg:grid-cols-2">{[['01','Problem',p.problem],['02','Solution',p.solution],['03','Engineering decisions',p.engineeringDecisions.join(' · ')],['04','Challenges',p.challenges.join(' · ')],['05','Lessons learned',p.lessonsLearned.join(' · ')],['06','Future improvements',p.futureImprovements.join(' · ') ]].map(([n,t,d])=><section key={n} className="card p-7"><span className="project-index">{n}</span><h2 className="mt-5 text-lg font-semibold">{t}</h2><p className="mt-3 text-sm leading-7 text-[#89969c]">{d}</p></section>)}</div><div className="mt-12 border-t border-[#182129] pt-8"><Link href="/contact" className="inline-flex items-center gap-2 text-sm font-semibold text-[#ff3b5c]">Discuss this project <ArrowUpRight size={14}/></Link></div></div></main></PageShell>}
